[kafka]
kafka01.atu.example.local kafka_broker_id=1
kafka02.atu.example.local kafka_broker_id=2
kafka03.atu.example.local kafka_broker_id=3

[kafka:vars]
ansible_user=ansible

[zookeeper]
zk01.atu.example.local zookeeper_id=1
zk02.atu.example.local zookeeper_id=2
zk03.atu.example.local zookeeper_id=3

[zookeeper:vars]
ansible_user=ansible
